name: Build Shared

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: autoconf
      run: ./autogen.sh --noconfigure
    - name: configure
      run: ./configure --enable-static --enable-shared --prefix=$(pwd)/build/shared/xar/
    - name: make
      run: make
    - name: make install
      run: make instal
    - name: make tarball
      run: tar cvzf xar-1.7.0-shared.tar.gz -C build/shared xar
