name: Build Static

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: autoconf
      run: ./autogen.sh --noconfigure
    - name: configure
      run: ./configure --enable-static --disable-shared --prefix=$(pwd)/build/static/xar/
    - name: make
      run: make
    - name: make install
      run: make instal
    - name: make tarball
      run: ar cvzf xar-1.7.0-static.tar.gz -C build/static xar
