name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Build Shared
      run: |
        ./autogen.sh --noconfigure
        ./configure --enable-static --enable-shared --prefix=$GITHUB_WORKSPACE/build/shared/xar/
        make
        make install
        tar cvzf xar-shared.tar.gz -C $GITHUB_WORKSPACE/build/shared xar
        make relclean
    - name: Build Static
      run: |
        ./autogen.sh --noconfigure
        ./configure --enable-static --disable-shared --prefix=$GITHUB_WORKSPACE/build/static/xar/
        make
        make install
        tar cvzf xar-static.tar.gz -C $GITHUB_WORKSPACE/build/static xar
    - name: Release
      id: create-release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          xar-shared.tar.gz
          xar-static.tar.gz
